Add Lego: Devopsy
voxpupuli/thevoxfox pull request #45
Opened 2016-12-31 22:04 UTC by sacres

Add pyquery to requirements. This Lego adds devopsreactions.

2016-12-31 22:09 UTC, sacres commented
Travis tests fail due to bandit  _false_ positive: [random](https://github.com/openstack/bandit/blob/a9f47e5d03df967804dadac37b1d5d95e8c8f6cf/bandit/blacklists/calls.py#L173)
That check is relative to crypto and not applicable in this instance.

2017-01-01 22:43 UTC, bbriggs requested changes

2017-01-01 22:43 UTC, bbriggs commented on Local/Devopsy.py
> +        key, val = random.choice(items)
Add a `#nosec` comment to the end of this line per https://github.com/openstack/bandit#exclusions since it's a false positive.

2017-01-01 23:51 UTC, bbriggs approved these changes

2017-01-01 23:51 UTC, merged

2017-01-02 00:02 UTC, sacres commented
Thanks @bbriggs!


On 01/01/2017 06:51 PM, Bren Briggs wrote:
>
> *@bbriggs* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/voxpupuli/thevoxfox/pull/45#pullrequestreview-14818888>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA4qOQ9o_yuvF_bnirE86iiesv35llPCks5rODwVgaJpZM4LYoE0>.
>